version: 2
updates:
  - package-ecosystem: "bundler"
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
      day: "wednesday"
      timezone: "America/Los_Angeles"
    cooldown:
      default-days: 7
    labels: []
    groups:
      minor-dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      # ignore all major version updates
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
