name: Relishable

on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.3', '3.4', '4.0' ]
    runs-on: pub-hk-ubuntu-24.04-medium

    name: Setup env & run tests

    steps:
    - name: Checkout repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Setup Ruby
      uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake spec
