name: Relishable

on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7' ]
    runs-on: ubuntu-22.04

    name: Setup env & run tests

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake spec
